Code edit
1. Removed app.use(express.json());
app.use(express.urlencoded({ extended: true })); from index.js

2. Added app.use(bodyParser.urlencoded({ extended: true })); to index.js below app.use(bodyParser.json()).

3.  Removed the following code,
const express = require('express');
and:
const router = express.Router();
from auth.js
3. Removed const { model } = require("mongoose"); from model.js

Server does not run on 8080, does not connect due to the following terminal error, let movieSchema = mongoose.Schema({
                  ^

ReferenceError: mongoose is not defined